# üîótrain set

In [4]:
# Train
import pandas as pd
dataframe = pd.read_csv('/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_10082023_splited_imgpath28_train.csv') #‡πÅ‡∏Å‡πâ data ‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡∏ï‡∏≤‡∏° fold
# dataframe = dataframe[dataframe['img_no'] ==1]
dataframe = dataframe.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])
print(dataframe.shape)
dataframe.head()

(180689, 12)

/home/yupaporn/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,path_img,img_no,branch,Path_folder_web,camera_angle,gender,category,work_by,status,clip_from,split,path_img_28
0,/media/hdd/tan/code/Show-Images/static/BearHou...,1,Fashion,BearHouse-Person/Fashion_ch3_20230310145957_20...,ch3,Men,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/Fashion_ch3_202303...
1,/media/hdd/tan/code/Show-Images/static/BearHou...,2,Fashion,BearHouse-Person/Fashion_ch3_20230310145957_20...,ch3,Men,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/Fashion_ch3_202303...
2,/media/hdd/tan/code/Show-Images/static/BearHou...,3,Fashion,BearHouse-Person/Fashion_ch3_20230310145957_20...,ch3,Men,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/Fashion_ch3_202303...
3,/media/hdd/tan/code/Show-Images/static/BearHou...,4,Fashion,BearHouse-Person/Fashion_ch3_20230310145957_20...,ch3,Men,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/Fashion_ch3_202303...
4,/media/hdd/tan/code/Show-Images/static/BearHou...,5,Fashion,BearHouse-Person/Fashion_ch3_20230310145957_20...,ch3,Men,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/Fashion_ch3_202303...

In [6]:
# Train
import pandas as pd
dataframe1 = pd.read_csv('/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_08102023_splited_imgpath28_train.csv') #‡πÅ‡∏Å‡πâ data ‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡∏ï‡∏≤‡∏° fold
# dataframe = dataframe[dataframe['img_no'] ==1]
dataframe1 = dataframe1.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])
print(dataframe1.shape)
dataframe1.head()

(9439, 12)

,path_img,img_no,branch,Path_folder_web,camera_angle,gender,category,work_by,status,clip_from,split,path_img_28
0,/media/hdd/tan/code/Show-Images/static/BearHou...,1,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Women,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
1,/media/hdd/tan/code/Show-Images/static/BearHou...,2,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Women,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
2,/media/hdd/tan/code/Show-Images/static/BearHou...,3,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Women,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
3,/media/hdd/tan/code/Show-Images/static/BearHou...,4,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Women,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
4,/media/hdd/tan/code/Show-Images/static/BearHou...,5,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Women,Student,Nat,NaN,Bear-House,train,/media/HDD/BearHouse-Person/kampu_ch4_20230310...

In [7]:
dataframe = dataframe.append(dataframe1)
print(dataframe.shape)

(190128, 12)

In [24]:
# path_men = dataframe['path_img_28'].tolist()
# path_men

In [8]:
img_no_df = dataframe[dataframe['Path_folder_web'] =='']
paths= list(set(dataframe['Path_folder_web']))
for i in range(len(paths)):
    dff = dataframe[dataframe['Path_folder_web'] ==paths[i]]
    image_no = int(len(dff)/2)
    img_no = dff[dff['img_no'] == image_no]
    img_no_df = img_no_df.append(img_no)
    
print(img_no_df.shape)
img_no_df.head()

path_men = img_no_df['path_img_28'].tolist()

(2683, 12)

In [9]:
import shutil
import os
path_men_new = []
img_new = []
train_dir = '/media/HDD/BearHouse-Person-Data/data_R3_middleframe/train/'
for i in range(len(path_men)):
    filename = str(i) + '_' + path_men[i].split('/')[-1]
    img_new.append(filename)
    filename_path = train_dir + filename
    path_men_new.append(filename_path)
    # moving image
    dst = os.path.join(train_dir,filename)
    shutil.copyfile(path_men[i], dst)

In [10]:
img_no_df['path_img_28_train'] = path_men_new
img_no_df['img_28_train'] = img_new
img_no_df.to_csv('/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_09102023_splited_imgpath28_train_middleframe.csv')

# üîóvaliodation set

In [11]:
# validation
import pandas as pd
valframe = pd.read_csv( '/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_10082023_splited_imgpath28_val.csv') #‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡∏ï‡∏≤‡∏° fold
print(valframe.shape)
valframe.head()

(45982, 14)

,Unnamed: 0,Unnamed: 0.1,path_img,img_no,branch,Path_folder_web,camera_angle,gender,category,work_by,status,clip_from,split,path_img_28
0,793,51,/media/hdd/tan/code/Show-Images/static/BearHou...,1,Camera17,BearHouse-Person/IP Camera17_kku2_kku2_2023061...,kku2,Men,Student,Yoke,NaN,Bear-House,val,/media/HDD/BearHouse-Person/IP Camera17_kku2_k...
1,794,28,/media/hdd/tan/code/Show-Images/static/BearHou...,2,Camera17,BearHouse-Person/IP Camera17_kku2_kku2_2023061...,kku2,Men,Student,Yoke,NaN,Bear-House,val,/media/HDD/BearHouse-Person/IP Camera17_kku2_k...
2,795,33,/media/hdd/tan/code/Show-Images/static/BearHou...,3,Camera17,BearHouse-Person/IP Camera17_kku2_kku2_2023061...,kku2,Men,Student,Yoke,NaN,Bear-House,val,/media/HDD/BearHouse-Person/IP Camera17_kku2_k...
3,796,42,/media/hdd/tan/code/Show-Images/static/BearHou...,4,Camera17,BearHouse-Person/IP Camera17_kku2_kku2_2023061...,kku2,Men,Student,Yoke,NaN,Bear-House,val,/media/HDD/BearHouse-Person/IP Camera17_kku2_k...
4,797,81,/media/hdd/tan/code/Show-Images/static/BearHou...,5,Camera17,BearHouse-Person/IP Camera17_kku2_kku2_2023061...,kku2,Men,Student,Yoke,NaN,Bear-House,val,/media/HDD/BearHouse-Person/IP Camera17_kku2_k...

In [12]:
# validation
import pandas as pd
valframe1 = pd.read_csv( '/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_08102023_splited_imgpath28_val.csv') #‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡∏ï‡∏≤‡∏° fold
print(valframe1.shape)
valframe1.head()

(987, 14)

,Unnamed: 0,Unnamed: 0.1,path_img,img_no,branch,Path_folder_web,camera_angle,gender,category,work_by,status,clip_from,split,path_img_28
0,0,94,/media/hdd/tan/code/Show-Images/static/BearHou...,1,siilom,BearHouse-Person/siilom_ch1_20230310130011_202...,ch1,Women,Student,Tan,NaN,Bear-House,val,/media/HDD/BearHouse-Person/siilom_ch1_2023031...
1,1,66,/media/hdd/tan/code/Show-Images/static/BearHou...,2,siilom,BearHouse-Person/siilom_ch1_20230310130011_202...,ch1,Women,Student,Tan,NaN,Bear-House,val,/media/HDD/BearHouse-Person/siilom_ch1_2023031...
2,2,14,/media/hdd/tan/code/Show-Images/static/BearHou...,3,siilom,BearHouse-Person/siilom_ch1_20230310130011_202...,ch1,Women,Student,Tan,NaN,Bear-House,val,/media/HDD/BearHouse-Person/siilom_ch1_2023031...
3,3,76,/media/hdd/tan/code/Show-Images/static/BearHou...,4,siilom,BearHouse-Person/siilom_ch1_20230310130011_202...,ch1,Women,Student,Tan,NaN,Bear-House,val,/media/HDD/BearHouse-Person/siilom_ch1_2023031...
4,4,47,/media/hdd/tan/code/Show-Images/static/BearHou...,5,siilom,BearHouse-Person/siilom_ch1_20230310130011_202...,ch1,Women,Student,Tan,NaN,Bear-House,val,/media/HDD/BearHouse-Person/siilom_ch1_2023031...

In [13]:
valframe = valframe.append(valframe1)
print(valframe.shape)

(46969, 14)

In [14]:
img_no_df = valframe[valframe['Path_folder_web'] =='']
paths= list(set(valframe['Path_folder_web']))
for i in range(len(paths)):
    dff = valframe[valframe['Path_folder_web'] ==paths[i]]
    image_no = int(len(dff)/2)
    img_no = dff[dff['img_no'] == image_no]
    img_no_df = img_no_df.append(img_no)
    
print(img_no_df.shape)
img_no_df.head()

path_men = img_no_df['path_img_28'].tolist()

(657, 14)

In [16]:
import shutil
import os
path_men_new = []
img_new = []
val_dir = '/media/HDD/BearHouse-Person-Data/data_R3_middleframe/validation/'

for i in range(len(path_men)):
    filename = str(i) + '_' + path_men[i].split('/')[-1]
    filename_path = val_dir + filename
    img_new.append(filename)
    path_men_new.append(filename_path)
    # moving image
    dst = os.path.join(val_dir,filename)
    shutil.copyfile(path_men[i], dst)
    
img_no_df['path_img_28_train'] = path_men_new
img_no_df['img_28_train'] = img_new
img_no_df.to_csv('/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_09102023_splited_imgpath28_val_middleframe.csv')

# üîótest set

In [17]:
#validation
import pandas as pd
testframe = pd.read_csv('/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_08102023_splited_imgpath28.csv') 
testframe = testframe[testframe['split'] =='test']
# testframe = testframe[testframe['img_no'] ==1]
print(testframe.shape)
testframe.head()

(40569, 14)

,Unnamed: 0,Unnamed: 0.1,path_img,img_no,branch,Path_folder_web,camera_angle,gender,category,work_by,status,clip_from,split,path_img_28
10426,10426,31,/media/hdd/tan/code/Show-Images/static/BearHou...,1,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Men,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
10427,10427,29,/media/hdd/tan/code/Show-Images/static/BearHou...,2,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Men,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
10428,10428,0,/media/hdd/tan/code/Show-Images/static/BearHou...,3,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Men,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
10429,10429,13,/media/hdd/tan/code/Show-Images/static/BearHou...,4,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Men,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/kampu_ch4_20230310...
10430,10430,22,/media/hdd/tan/code/Show-Images/static/BearHou...,5,kampu,BearHouse-Person/kampu_ch4_20230310150002_2023...,ch4,Men,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/kampu_ch4_20230310...

In [18]:
#validation
import pandas as pd
testframe1 = pd.read_csv('/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_10082023_splited_imgpath28.csv') 
testframe1 = testframe1[testframe1['split'] =='test']
# testframe = testframe[testframe['img_no'] ==1]
print(testframe1.shape)
testframe1.head()

(56520, 14)

/home/yupaporn/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Unnamed: 0.1,path_img,img_no,branch,Path_folder_web,camera_angle,gender,category,work_by,status,clip_from,split,path_img_28
226671,226671,31,/media/hdd/tan/code/Show-Images/static/BearHou...,1,CCON,BearHouse-Person/CCON_ch7_20230310130001_20230...,ch7,Women,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/CCON_ch7_202303101...
226672,226672,27,/media/hdd/tan/code/Show-Images/static/BearHou...,2,CCON,BearHouse-Person/CCON_ch7_20230310130001_20230...,ch7,Women,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/CCON_ch7_202303101...
226673,226673,23,/media/hdd/tan/code/Show-Images/static/BearHou...,3,CCON,BearHouse-Person/CCON_ch7_20230310130001_20230...,ch7,Women,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/CCON_ch7_202303101...
226674,226674,6,/media/hdd/tan/code/Show-Images/static/BearHou...,4,CCON,BearHouse-Person/CCON_ch7_20230310130001_20230...,ch7,Women,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/CCON_ch7_202303101...
226675,226675,28,/media/hdd/tan/code/Show-Images/static/BearHou...,5,CCON,BearHouse-Person/CCON_ch7_20230310130001_20230...,ch7,Women,Working,Nat,NaN,Bear-House,test,/media/HDD/BearHouse-Person/CCON_ch7_202303101...

In [19]:
testframe = testframe.append(testframe1)
print(testframe.shape)

(97089, 14)

In [20]:
img_no_df = testframe[testframe['Path_folder_web'] =='']
paths= list(set(testframe['Path_folder_web']))
for i in range(len(paths)):
    dff = testframe[testframe['Path_folder_web'] ==paths[i]]
    image_no = int(len(dff)/2)
    img_no = dff[dff['img_no'] == image_no]
    img_no_df = img_no_df.append(img_no)
    
print(img_no_df.shape)
img_no_df.head()

path_men = img_no_df['path_img_28'].tolist()

(1299, 14)

In [21]:
import shutil
import os
path_men_new = []
img_new = []
val_dir = '/media/HDD/BearHouse-Person-Data/data_R3_middleframe/test/'

for i in range(len(path_men)):
    filename = str(i) + '_' + path_men[i].split('/')[-1]
    filename_path = val_dir + filename
    img_new.append(filename)
    path_men_new.append(filename_path)
    # moving image
    dst = os.path.join(val_dir,filename)
    shutil.copyfile(path_men[i], dst)
    
img_no_df['path_img_28_train'] = path_men_new
img_no_df['img_28_train'] = img_new
img_no_df.to_csv('/home/yupaporn/code/EffNet-Person-Classify/data_label_by_tan_09102023_splited_imgpath28_test_middleframe.csv')